name: web_prototype
description: A new Flutter application
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_database:
  flutter_barcode_scanner: ^1.0.1
  font_awesome_flutter:
  razorpay_flutter: ^1.2.2
  toast: ^0.1.5
#  flutter_rave:
#   git:
#      url: https://github.com/demimola24/flutter_rave.git
#      ref: master

  fl_chart:
  charts_flutter:
  shimmer: ^1.1.2
  page_transition: '^1.0.9'
  introduction_screen: ^1.0.7
  url_launcher:
    #Maps
#  fl_chart:
#  charts_flutter:
#  shimmer: ^1.1.2
#  page_transition: '^1.0.9'
#  introduction_screen: ^1.0.7
  rxdart:
#  url_launcher:

  geoflutterfire:

  location:
  google_maps_flutter:

  geocoder:
  geolocator: ^7.6.0

  # other dependencies
  kommunicate_flutter: ^1.2.0

  #AWS Chat bot
  http: ^0.13.3
  sigv4: ^5.0.0
  uuid: ^3.0.4
  flutter_chat_ui: ^1.3.3

  #YM Bot
  #ym_flutter_integration: 0.1.0

  #Alan voice bot
  alan_voice: ^2.4.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logoWhte.jpeg"
flutter_launcher_name:
  name: "Golden Key"




  #Font
  font_awesome_flutter:
  razorpay_flutter: ^1.2.2
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true



  assets:
    - images/logoWhte.jpeg
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf
